// src/constants/courses.ts
export const COURSES = [
  // ========== FOREX COURSES ==========
  {
    id: 1,
    slug: "forex-trading",
    title: "Forex Trading",
    category: "forex",
    shortDesc: "Master Smart Money Concepts, interbank liquidity patterns, and advanced risk engineering frameworks.",
    duration: "12 Weeks",
    isFlagship: true,
  },
  {
    id: 2,
    slug: "advanced-forex",
    title: "Advanced Forex Trading",
    category: "forex",
    shortDesc: "Master price action, risk management, and advanced trading strategies.",
    duration: "12 Weeks",
    isFlagship: false,
  },
  {
    id: 3,
    slug: "crypto-trading",
    title: "Crypto Trading Essentials",
    category: "forex",
    shortDesc: "Learn cryptocurrency markets, technical analysis, and portfolio management.",
    duration: "8 Weeks",
    isFlagship: false,
  },

  // ========== TECH COURSES ==========
  {
    id: 4,
    slug: "cyber-security",
    title: "Cyber Security",
    category: "tech",
    shortDesc: "Deploy penetration architectures, perform OWASP threat scans, and secure server networking structures.",
    duration: "8 Weeks",
    isFlagship: false,
  },
  {
    id: 5,
    slug: "web-development",
    title: "Web Development",
    category: "tech",
    shortDesc: "Build lightning-fast responsive full-stack applications with React, Tailwind CSS, Express, and databases.",
    duration: "10 Weeks",
    isFlagship: false,
  },
  {
    id: 6,
    slug: "full-stack-development",
    title: "Full Stack Web Development",
    category: "tech",
    shortDesc: "Build complete web applications using modern frontend and backend technologies.",
    duration: "16 Weeks",
    isFlagship: true,
  },
  {
    id: 7,
    slug: "mobile-app-development",
    title: "Mobile App Development",
    category: "tech",
    shortDesc: "Create Android and iOS apps using modern development frameworks.",
    duration: "14 Weeks",
    isFlagship: false,
  },
  {
    id: 8,
    slug: "python-programming",
    title: "Python Programming",
    category: "tech",
    shortDesc: "Learn Python for automation, web development, and data analysis.",
    duration: "10 Weeks",
    isFlagship: false,
  },

  // ========== MARKETING COURSES ==========
  {
    id: 9,
    slug: "digital-marketing",
    title: "Digital Marketing",
    category: "marketing",
    shortDesc: "Master SEO, social media marketing, paid advertising, and content strategy.",
    duration: "10 Weeks",
    isFlagship: false,
  },
  {
    id: 10,
    slug: "meta-ads",
    title: "Meta Ads Mastery",
    category: "marketing",
    shortDesc: "Learn Facebook and Instagram advertising for business growth.",
    duration: "6 Weeks",
    isFlagship: false,
  },
  {
    id: 11,
    slug: "google-ads",
    title: "Google Ads",
    category: "marketing",
    shortDesc: "Run high-converting search and display advertising campaigns.",
    duration: "6 Weeks",
    isFlagship: false,
  },

  // ========== CREATIVE COURSES ==========
  {
    id: 12,
    slug: "graphic-design",
    title: "Graphic Design",
    category: "creative",
    shortDesc: "Design professional branding, social media posts, and marketing materials.",
    duration: "8 Weeks",
    isFlagship: false,
  },
  {
    id: 13,
    slug: "video-editing",
    title: "Video Editing",
    category: "creative",
    shortDesc: "Create engaging videos using industry-standard editing software.",
    duration: "8 Weeks",
    isFlagship: false,
  },
  {
    id: 14,
    slug: "ui-ux-design",
    title: "UI/UX Design",
    category: "creative",
    shortDesc: "Design intuitive interfaces and engaging digital experiences.",
    duration: "10 Weeks",
    isFlagship: false,
  },

  // ========== ACADEMICS & IELTS COURSES ==========
  {
    id: 15,
    slug: "ielts-preparation",
    title: "IELTS Preparation",
    category: "academic",
    shortDesc: "Comprehensive preparation for Listening, Reading, Writing, and Speaking modules.",
    duration: "8 Weeks",
    isFlagship: true,
  },
  {
    id: 16,
    slug: "spoken-english",
    title: "Spoken English",
    category: "academic",
    shortDesc: "Improve communication skills, fluency, pronunciation, and confidence.",
    duration: "6 Weeks",
    isFlagship: false,
  },
  {
    id: 17,
    slug: "academic-writing",
    title: "Academic Writing",
    category: "academic",
    shortDesc: "Develop professional writing skills for university and career success.",
    duration: "6 Weeks",
    isFlagship: false,
  },
];